[I 210401 14:51:25 command:134] Visit me at http://localhost:5555
[I 210401 14:51:25 command:141] Broker: redis://:**@redis:6379/3
[I 210401 14:51:25 command:142] Registered tasks: 
    ['assets.tasks.admin_user_connectivity.test_admin_user_connectivity_manual',
     'assets.tasks.admin_user_connectivity.test_admin_user_connectivity_period',
     'assets.tasks.asset_connectivity.test_asset_connectivity_manual',
     'assets.tasks.asset_connectivity.test_asset_connectivity_util',
     'assets.tasks.asset_connectivity.test_assets_connectivity_manual',
     'assets.tasks.asset_connectivity.test_node_assets_connectivity_manual',
     'assets.tasks.asset_user_connectivity.push_asset_user_util',
     'assets.tasks.asset_user_connectivity.test_asset_users_connectivity_manual',
     'assets.tasks.common.add_nodes_assets_to_system_users',
     'assets.tasks.gather_asset_hardware_info.update_asset_hardware_info_manual',
     'assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_manual',
     'assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_period',
     'assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_util',
     'assets.tasks.gather_asset_hardware_info.update_node_assets_hardware_info_manual',
     'assets.tasks.gather_asset_users.gather_asset_users',
     'assets.tasks.gather_asset_users.gather_nodes_asset_users',
     'assets.tasks.nodes_amount.check_node_assets_amount_period_task',
     'assets.tasks.nodes_amount.check_node_assets_amount_task',
     'assets.tasks.push_system_user.push_system_user_a_asset_manual',
     'assets.tasks.push_system_user.push_system_user_to_assets',
     'assets.tasks.push_system_user.push_system_user_to_assets_manual',
     'assets.tasks.system_user_connectivity.test_system_user_connectivity_a_asset',
     'assets.tasks.system_user_connectivity.test_system_user_connectivity_manual',
     'assets.tasks.system_user_connectivity.test_system_user_connectivity_period',
     'audits.tasks.clean_audits_log_period',
     'audits.tasks.clean_ftp_log_period',
     'audits.tasks.clean_login_log_period',
     'audits.tasks.clean_operation_log_period',
     'authentication.tasks.clean_django_sessions',
     'celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'common.tasks.send_mail_async',
     'ops.tasks.add',
     'ops.tasks.add_m',
     'ops.tasks.check_server_performance_period',
     'ops.tasks.clean_celery_periodic_tasks',
     'ops.tasks.clean_celery_tasks_period',
     'ops.tasks.clean_tasks_adhoc_period',
     'ops.tasks.create_or_update_registered_periodic_tasks',
     'ops.tasks.hello',
     'ops.tasks.hello123',
     'ops.tasks.hello_callback',
     'ops.tasks.run_ansible_task',
     'ops.tasks.run_command_execution',
     'orgs.tasks.refresh_org_cache_task',
     'perms.tasks.check_asset_permission_expired',
     'terminal.tasks.clean_expired_session_period',
     'terminal.tasks.clean_orphan_session',
     'terminal.tasks.delete_terminal_status_period',
     'terminal.tasks.upload_session_replay_to_external_storage',
     'users.tasks.check_password_expired',
     'users.tasks.check_password_expired_periodic',
     'users.tasks.check_user_expired',
     'users.tasks.check_user_expired_periodic',
     'users.tasks.import_ldap_user',
     'users.tasks.import_ldap_user_periodic']
[I 210401 14:51:25 mixins:229] Connected to redis://:**@redis:6379/3
[W 210401 14:51:30 control:43] 'stats' inspect method failed
[W 210401 14:51:30 control:43] 'active_queues' inspect method failed
[W 210401 14:51:30 control:43] 'registered' inspect method failed
[W 210401 14:51:30 control:43] 'scheduled' inspect method failed
[W 210401 14:51:30 control:43] 'active' inspect method failed
[W 210401 14:51:30 control:43] 'reserved' inspect method failed
[W 210401 14:51:30 control:43] 'revoked' inspect method failed
[W 210401 14:51:30 control:43] 'conf' inspect method failed
[I 210401 14:53:21 command:134] Visit me at http://localhost:5555
[I 210401 14:53:21 command:141] Broker: redis://:**@redis:6379/3
[I 210401 14:53:21 command:142] Registered tasks: 
    ['assets.tasks.admin_user_connectivity.test_admin_user_connectivity_manual',
     'assets.tasks.admin_user_connectivity.test_admin_user_connectivity_period',
     'assets.tasks.asset_connectivity.test_asset_connectivity_manual',
     'assets.tasks.asset_connectivity.test_asset_connectivity_util',
     'assets.tasks.asset_connectivity.test_assets_connectivity_manual',
     'assets.tasks.asset_connectivity.test_node_assets_connectivity_manual',
     'assets.tasks.asset_user_connectivity.push_asset_user_util',
     'assets.tasks.asset_user_connectivity.test_asset_users_connectivity_manual',
     'assets.tasks.common.add_nodes_assets_to_system_users',
     'assets.tasks.gather_asset_hardware_info.update_asset_hardware_info_manual',
     'assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_manual',
     'assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_period',
     'assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_util',
     'assets.tasks.gather_asset_hardware_info.update_node_assets_hardware_info_manual',
     'assets.tasks.gather_asset_users.gather_asset_users',
     'assets.tasks.gather_asset_users.gather_nodes_asset_users',
     'assets.tasks.nodes_amount.check_node_assets_amount_period_task',
     'assets.tasks.nodes_amount.check_node_assets_amount_task',
     'assets.tasks.push_system_user.push_system_user_a_asset_manual',
     'assets.tasks.push_system_user.push_system_user_to_assets',
     'assets.tasks.push_system_user.push_system_user_to_assets_manual',
     'assets.tasks.system_user_connectivity.test_system_user_connectivity_a_asset',
     'assets.tasks.system_user_connectivity.test_system_user_connectivity_manual',
     'assets.tasks.system_user_connectivity.test_system_user_connectivity_period',
     'audits.tasks.clean_audits_log_period',
     'audits.tasks.clean_ftp_log_period',
     'audits.tasks.clean_login_log_period',
     'audits.tasks.clean_operation_log_period',
     'authentication.tasks.clean_django_sessions',
     'celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'common.tasks.send_mail_async',
     'ops.tasks.add',
     'ops.tasks.add_m',
     'ops.tasks.check_server_performance_period',
     'ops.tasks.clean_celery_periodic_tasks',
     'ops.tasks.clean_celery_tasks_period',
     'ops.tasks.clean_tasks_adhoc_period',
     'ops.tasks.create_or_update_registered_periodic_tasks',
     'ops.tasks.hello',
     'ops.tasks.hello123',
     'ops.tasks.hello_callback',
     'ops.tasks.run_ansible_task',
     'ops.tasks.run_command_execution',
     'orgs.tasks.refresh_org_cache_task',
     'perms.tasks.check_asset_permission_expired',
     'terminal.tasks.clean_expired_session_period',
     'terminal.tasks.clean_orphan_session',
     'terminal.tasks.delete_terminal_status_period',
     'terminal.tasks.upload_session_replay_to_external_storage',
     'users.tasks.check_password_expired',
     'users.tasks.check_password_expired_periodic',
     'users.tasks.check_user_expired',
     'users.tasks.check_user_expired_periodic',
     'users.tasks.import_ldap_user',
     'users.tasks.import_ldap_user_periodic']
[I 210401 14:53:21 mixins:229] Connected to redis://:**@redis:6379/3
[W 210401 14:53:26 control:43] 'stats' inspect method failed
[W 210401 14:53:26 control:43] 'active_queues' inspect method failed
[W 210401 14:53:26 control:43] 'registered' inspect method failed
[W 210401 14:53:26 control:43] 'scheduled' inspect method failed
[W 210401 14:53:26 control:43] 'active' inspect method failed
[W 210401 14:53:26 control:43] 'reserved' inspect method failed
[W 210401 14:53:26 control:43] 'revoked' inspect method failed
[W 210401 14:53:26 control:43] 'conf' inspect method failed
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/opt/jumpserver/apps/settings/signals_handler.py", line 75, in keep_subscribe
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    for msg in sub.listen():
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3605, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/jumpserver/apps/orgs/signals_handler/common.py", line 50, in keep_subscribe
    for message in subscribe.listen():
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3605, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[E 210401 15:32:59 events:123] Failed to capture events: 'Connection closed by server.', trying again in 1 seconds.
    self._target(*self._args, **self._kwargs)
  File "/opt/jumpserver/apps/assets/signals_handler/node_assets_mapping.py", line 77, in keep_subscribe
    for message in subscribe.listen():
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3605, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[I 210401 15:36:00 command:134] Visit me at http://localhost:5555
[I 210401 15:36:00 command:141] Broker: redis://:**@redis:6379/3
[I 210401 15:36:00 command:142] Registered tasks: 
    ['assets.tasks.admin_user_connectivity.test_admin_user_connectivity_manual',
     'assets.tasks.admin_user_connectivity.test_admin_user_connectivity_period',
     'assets.tasks.asset_connectivity.test_asset_connectivity_manual',
     'assets.tasks.asset_connectivity.test_asset_connectivity_util',
     'assets.tasks.asset_connectivity.test_assets_connectivity_manual',
     'assets.tasks.asset_connectivity.test_node_assets_connectivity_manual',
     'assets.tasks.asset_user_connectivity.push_asset_user_util',
     'assets.tasks.asset_user_connectivity.test_asset_users_connectivity_manual',
     'assets.tasks.common.add_nodes_assets_to_system_users',
     'assets.tasks.gather_asset_hardware_info.update_asset_hardware_info_manual',
     'assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_manual',
     'assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_period',
     'assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_util',
     'assets.tasks.gather_asset_hardware_info.update_node_assets_hardware_info_manual',
     'assets.tasks.gather_asset_users.gather_asset_users',
     'assets.tasks.gather_asset_users.gather_nodes_asset_users',
     'assets.tasks.nodes_amount.check_node_assets_amount_period_task',
     'assets.tasks.nodes_amount.check_node_assets_amount_task',
     'assets.tasks.push_system_user.push_system_user_a_asset_manual',
     'assets.tasks.push_system_user.push_system_user_to_assets',
     'assets.tasks.push_system_user.push_system_user_to_assets_manual',
     'assets.tasks.system_user_connectivity.test_system_user_connectivity_a_asset',
     'assets.tasks.system_user_connectivity.test_system_user_connectivity_manual',
     'assets.tasks.system_user_connectivity.test_system_user_connectivity_period',
     'audits.tasks.clean_audits_log_period',
     'audits.tasks.clean_ftp_log_period',
     'audits.tasks.clean_login_log_period',
     'audits.tasks.clean_operation_log_period',
     'authentication.tasks.clean_django_sessions',
     'celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'common.tasks.send_mail_async',
     'ops.tasks.add',
     'ops.tasks.add_m',
     'ops.tasks.check_server_performance_period',
     'ops.tasks.clean_celery_periodic_tasks',
     'ops.tasks.clean_celery_tasks_period',
     'ops.tasks.clean_tasks_adhoc_period',
     'ops.tasks.create_or_update_registered_periodic_tasks',
     'ops.tasks.hello',
     'ops.tasks.hello123',
     'ops.tasks.hello_callback',
     'ops.tasks.run_ansible_task',
     'ops.tasks.run_command_execution',
     'orgs.tasks.refresh_org_cache_task',
     'perms.tasks.check_asset_permission_expired',
     'terminal.tasks.clean_expired_session_period',
     'terminal.tasks.clean_orphan_session',
     'terminal.tasks.delete_terminal_status_period',
     'terminal.tasks.upload_session_replay_to_external_storage',
     'users.tasks.check_password_expired',
     'users.tasks.check_password_expired_periodic',
     'users.tasks.check_user_expired',
     'users.tasks.check_user_expired_periodic',
     'users.tasks.import_ldap_user',
     'users.tasks.import_ldap_user_periodic']
[I 210401 15:36:00 mixins:229] Connected to redis://:**@redis:6379/3
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/jumpserver/apps/settings/signals_handler.py", line 75, in keep_subscribe
    for msg in sub.listen():
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3605, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/jumpserver/apps/orgs/signals_handler/common.py", line 50, in keep_subscribe
    for message in subscribe.listen():
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3605, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/jumpserver/apps/assets/signals_handler/node_assets_mapping.py", line 77, in keep_subscribe
    for message in subscribe.listen():
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3605, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[E 210401 15:37:58 events:123] Failed to capture events: 'Connection closed by server.', trying again in 1 seconds.
